# Railway Configuration for AI Career Coach

# Backend API Service
[build]
builder = "NIXPACKS"
buildCommand = "cd backend && npm install && npm run prisma:generate && npm run build"

[deploy]
startCommand = "cd backend && npm run start:migrate"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Worker Service for Resume Parsing
[[services]]
name = "worker-resume-parser"
buildCommand = "cd backend && npm install && npm run prisma:generate && npm run build"
startCommand = "cd backend && npm run start:worker"
watchPatterns = ["backend/**"]

[[services.healthcheck]]
path = "/health"
timeout = 60
interval = 30
