# Railway Configuration
# Start commands are set per-service in Railway UI to allow different commands
# Backend: npm run start:migrate
# Worker: npm run start:worker

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
