# Backend API Service
[deploy]
startCommand = "npm run start:migrate"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Worker Service for Resume Parsing
[[services]]
name = "worker-resume-parser"
buildCommand = "npm install && npm run prisma:generate && npm run build"
startCommand = "npm run start:worker"

[[services.healthcheck]]
path = "/health"
timeout = 60
interval = 30
