# Railway Configuration
# Start commands are set per-service in Railway UI to allow different commands
# Backend: npm run start:migrate
# Worker: npm run start:worker

[build]
# Prevent Railway from detecting/building the frontend directory
# Frontend should be deployed separately on Vercel
builder = "NIXPACKS"
buildCommand = "npm install && rm -rf node_modules/.prisma && npx prisma generate && npm run build"

[deploy]
startCommand = "npm run start:migrate"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Only watch backend directory for changes
watchPaths = ["backend/**"]
